name: navigine_sdk
description: A Flutter plugin for integrating NavigineSDK in Android and iOS applications.
version: 3.3.1
homepage: https://github.com/Navigine/navigine_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter_plugin_android_lifecycle: ^2.0.6
  equatable: ^2.0.3
  collection: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: com.navigine.naviginesdk
        pluginClass: NavigineSdkPlugin
      ios:
        pluginClass: NavigineSdkPlugin
